# Generated by Django 5.1.5 on 2025-02-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
