# Generated by Django 5.1.5 on 2025-02-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_file_upload_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
