# Generated by Django 5.1.5 on 2025-02-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_app', '0003_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=1024)),
                ('upload_timestamp', models.IntegerField(default=0)),
            ],
        ),
    ]
