# Generated by Django 5.1.5 on 2025-02-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
