# Generated by Django 5.1.5 on 2025-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0005_alter_file_file_type_alter_file_upload_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
